version: '2.4'

networks:
  fabric-net:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:2.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/hyperledger/orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ordererdata:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    extra_hosts:
      - "peer0.org2.example.com:72.61.113.7"
    networks:
      - fabric-net


  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    working_dir: /opt/hyperledger/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/peer/msp
      - ./organizations/peerOrganizations/org1.example.com/users:/var/hyperledger/peer/users
      - ./chaincode:/opt/gopath/src/github.com/chaincode
    ports:
      - 7051:7051
      - 7053:7053
    extra_hosts:
      - "peer0.org2.example.com:72.61.113.7"
      - "orderer.example.com:178.16.139.239"
    networks:
      - fabric-net


  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4
    tty: true
    stdin_open: true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    environment:
      - FABRIC_CFG_PATH=/opt/hyperledger/fabric/configtx
    volumes:
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./configtx:/opt/hyperledger/fabric/configtx
      - ./organizations:/opt/hyperledger/fabric/organizations  
    extra_hosts:
      - "peer0.org2.example.com:72.61.113.7"
      - "orderer.example.com:178.16.139.239"
    networks:
      - fabric-net

volumes:
  ordererdata:
