version: "2.4"

networks:
  fabric-net:

services:
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
    working_dir: /opt/hyperledger/peer
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/peer/msp
      - ./organizations/peerOrganizations/org2.example.com/users:/var/hyperledger/peer/users
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./organizations:/opt/hyperledger/fabric/organizations
      - ./organizations:/etc/hyperledger/organizations
      - peer0org2data:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
    extra_hosts:
      - "orderer.example.com:3.27.144.169"
      - "peer0.org1.example.com:3.27.144.169"
    networks:
      - fabric-net

  cli_org2:
    container_name: cli_org2
    image: hyperledger/fabric-tools:2.4
    tty: true
    stdin_open: true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer

    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric # peer + core.yaml

    volumes:
      # peer CLI paths
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./chaincode:/opt/gopath/src/github.com/chaincode

      # configtxgen profile loader
      - ./configtx:/opt/hyperledger/fabric/configtx

      # core.yaml + configtx.yaml for peer & configtxgen
      - ./configtx/configtx.yaml:/etc/hyperledger/fabric/configtx.yaml

      # TLS & MSP load path for configtxgen
      - ./organizations:/opt/hyperledger/fabric/organizations
      - ./organizations:/etc/hyperledger/organizations

    extra_hosts:
      - "orderer.example.com:3.27.144.169"
      - "peer0.org1.example.com:3.27.144.169"
      - "peer0.org2.example.com:178.16.139.239"

    networks:
      - fabric-net

volumes:
  peer0org2data:
